# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretEnvManager < Formula
  desc ""
  homepage ""
  version "2024.03.15"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gumi/secret-env-manager/releases/download/2024.03.15/secret-env-manager_Darwin_arm64.tar.gz"
      sha256 "1c82e88c86e3c2e603d384b7516833508b79812de2404d368450cccd5b4abc4a"

      def install
        bin.install "sem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gumi/secret-env-manager/releases/download/2024.03.15/secret-env-manager_Darwin_x86_64.tar.gz"
      sha256 "35c0d4b68b439f5e6c77088f0dde84dcd9110acc5c7fcde45ce68f8b7703f35b"

      def install
        bin.install "sem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gumi/secret-env-manager/releases/download/2024.03.15/secret-env-manager_Linux_arm64.tar.gz"
      sha256 "4d5aea701cdd5b4b2a337cbb4b284fa7ba2c464f5424801adb50c329d8051bf4"

      def install
        bin.install "sem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gumi/secret-env-manager/releases/download/2024.03.15/secret-env-manager_Linux_x86_64.tar.gz"
      sha256 "895e5e8416463b95d3f381c6a7508a34d9296dcef791118b8a4655a57d3a77e9"

      def install
        bin.install "sem"
      end
    end
  end
end
