# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretEnvManager < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gumi/secret-env-manager/releases/download/1.0.0/secret-env-manager_Darwin_x86_64.zip"
      sha256 "add662ec9d79ef8831fd44281477894d8d430a302114fa46c448476f3eebb37d"

      def install
        bin.install "sem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gumi/secret-env-manager/releases/download/1.0.0/secret-env-manager_Darwin_arm64.zip"
      sha256 "ca07b4424640de84cb9ca1c15ef60917dcdedcdb4d42ff9bbdb2ade89b1ede83"

      def install
        bin.install "sem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gumi/secret-env-manager/releases/download/1.0.0/secret-env-manager_Linux_x86_64.zip"
      sha256 "0586a5614bbaca0170ab1c076fc1c911c80515deca0480e85684b72b8cffe067"
      def install
        bin.install "sem"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gumi/secret-env-manager/releases/download/1.0.0/secret-env-manager_Linux_arm64.zip"
      sha256 "f5ea226846be50631d9112e09b278fced6d1d48886f497e4a20c4b7cebe27d5d"
      def install
        bin.install "sem"
      end
    end
  end
end
